FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY framp.me.pem /etc/ssl/framp.me.pem
COPY framp.me.key /etc/ssl/framp.me.key
COPY proddef.com.pem /etc/ssl/proddef.com.pem
COPY proddef.com.key /etc/ssl/proddef.com.key
RUN echo "fuck you 2"
